{% set name = "nettle" %}
{% set version = "3.8" %}
{% set sha256 = "7576c68481c198f644b08c160d1a4850ba9449e308069455b5213319f234e8e6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://ftp.gnu.org/gnu/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [win]
  run_exports:
    # https://abi-laboratory.pro/?view=timeline&l=nettle
    - {{ pin_subpackage('nettle', max_pin='x.x') }}

requirements:
  build:
    - libtool  # [unix]
    - {{ compiler('c') }}
    - autoconf
    - m4
    - make

test:
  commands:
    - test -f ${PREFIX}/lib/libnettle${SHLIB_EXT}
    - test -f ${PREFIX}/lib/libhogweed${SHLIB_EXT}
    - test ! -f ${PREFIX}/lib/libnettle.a
    - test ! -f ${PREFIX}/lib/libhogweed.a
#  downstreams:
#    - gnutls

about:
  home: https://www.lysator.liu.se/~nisse/nettle/
  license: GPL 2 and LGPL3
  license_family: GPL
  license_file: {{ environ["RECIPE_DIR"] }}/LICENSE
  summary: Nettle is a low-level cryptographic library that is designed to fit easily in more or less any context
  description: Nettle is a low-level cryptographic library that is designed to fit easily in more or less any context. In crypto toolkits for object-oriented languages (C++, Python, Pike, ...), in applications like LSH or GNUPG, or even in kernel space. Simple, fast, extensible JSON encoder/decoder for Python

  doc_url: https://www.lysator.liu.se/~nisse/nettle/nettle.html
  dev_url: https://git.lysator.liu.se/nettle/nettle

extra:
  recipe-maintainers:
    - sachalau
    - erykoff
