schema_version: 1

context:
  name: nettle
  version: 3.10.1

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://ftp.gnu.org/gnu/${{ name }}/${{ name }}-${{ version }}.tar.gz
  sha256: b0fcdd7fc0cdea6e80dcf1dd85ba794af0d5b4a57e26397eee3bc193272d9132

build:
  number: 0
  skip: win

requirements:
  build:
    - if: unix
      then: libtool
    - ${{ compiler('c') }}
    - ${{ stdlib("c") }}
    - autoconf
    - m4
    - make
  run_exports:
    - ${{ pin_subpackage('nettle', upper_bound='x.x') }}

tests:
  - script:
      - test -f ${PREFIX}/lib/libnettle${SHLIB_EXT}
      - test -f ${PREFIX}/lib/libhogweed${SHLIB_EXT}
      - test ! -f ${PREFIX}/lib/libnettle.a
      - test ! -f ${PREFIX}/lib/libhogweed.a

about:
  license: GPL-2.0-or-later OR LGPL-3.0-or-later
  license_file: LICENSE
  summary: Nettle is a low-level cryptographic library that is designed to fit easily in more or less any context
  description: |
    Nettle is a low-level cryptographic library that is designed to fit easily in more or less any context.
    In crypto toolkits for object-oriented languages (C++, Python, Pike, ...), in applications like LSH or GNUPG, or even in kernel space.
    Simple, fast, extensible JSON encoder/decoder for Python
  homepage: https://www.lysator.liu.se/~nisse/nettle/
  repository: https://git.lysator.liu.se/nettle/nettle
  documentation: https://www.lysator.liu.se/~nisse/nettle/nettle.html

extra:
  recipe-maintainers:
    - sachalau
    - erykoff
