appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: Z0UsFnokYKV1X+aO/t1/868kEyIZfFjF3Uty3XE8eRmtdgHijZzoQX47Q1yjeaTY+kRv94g0YvSaRPuVRm5l/Wp7DKvGepE4St9mjxGa3UbOsenrcwkq5SuPxyvosKa3l6zNpVjhQtASaKfbxBufvmbCDbIiM5fsE362BHGy3XZvPZAIS9gsrHlrsN69u1rSJoMAlOCsyPnjlK/s07gfM2Aru6arSwROaWZX+54CFzaVc106Hb8EqENi51M8qGgGitIr5DRs5NascyDeS0BJnP2273PFviw9bmi340cIj1x1gml/9CL2Jl+u82qR9IPFShyDX9GGG4Ia6mWLM7S3tH0YueorzddGZfGzonKL+bhsFCMxxaMikNY5/PeBkWTJoxcUT+RM6mRh7eJvcUJJXOzMf7hIfIEi0yEWvTEr0r0IJwxJQCKTNvlAmGNIQnNUyexFa21R6Xn1otDH4/tCzag2fMUGYscgHiVWqc8Mj3qbUDD/KrhpSRAjBH/PD2ShnU9TnVd0cc22wtg8MiBxV586Ic0AvXs8cQW8A4bq5e7rEXZ+8mfWoF2/+QBCkzVSjQiHhlAOkl2LMdS5akDHfSc+VuSLmTElH0XR+1avFZmke4ebOElnRvcQ/F3MgCmDdGaty+UiA96d0RjAxdaW9yRnxfDuD+2v0eQAGvqbq+I=}
